#
FROM base-rocky8.5
ENV ARMCI_NETWORK=MPI-PR
ENV NWCHEM_TOP=/apps/nwchem-7.0.2-release
ENV NWCHEM_TARGET=LINUX64
ENV NWCHEM_MODULES="all"
ENV BLASOPT=" -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core  -lpthread -lutil -lm -ldl"
ENV LAPACK_LIB="-lmkl_intel_ilp64 -lmkl_sequential -lmkl_core  -lpthread -lutil -lm -ldl"
ENV SCALAPACK_LIB=" -lmkl_scalapack_ilp64 -lmkl_blacs_intelmpi_ilp64 -lpthread -lutil -lm -ldl"
ENV BLAS_SIZE=8
ENV SCALAPACK_SIZE=8
ENV USE_64TO32=y
ENV USE_FPICF=y
ENV USE_MPI=y
ENV USE_MPIF=y
ENV USE_MPIF4=y
ENV FC=ifort
ENV CC=icc
ENV CXX=icpc
RUN yum install -y  pkgconfig wget make git curl wget openssl-devel glibc-devel which \
&& mkdir -pv /apps \
&& bash -c "source /opt/intel/oneapi/setvars.sh  \
&& cd /apps ;curl -SL   https://github.com/nwchemgit/nwchem/archive/refs/tags/v7.0.2-release.tar.gz  | tar xzf - \
&& cd $NWCHEM_TOP/src \
&&  sed -i 's/nb=500/nb=1000/g' atomscf/cguess.fh \
&& make FC=ifort CC=icc CXX=icpc" \
&& mkdir -pv /apps/nwchem/bin \
&& mkdir -pv /apps/nwchem/data \
&& cp $NWCHEM_TOP/bin/${NWCHEM_TARGET}/nwchem /apps/nwchem/bin \
&& cd /apps/nwchem/bin \
&& chmod 755 nwchem \
&& cd $NWCHEM_TOP/src/basis \
&& cp -r libraries /apps/nwchem/data \
&& cd $NWCHEM_TOP/src \
&& cp -r data /apps/nwchem/ \
&& cd $NWCHEM_TOP/src/nwpw \
&& cp -r libraryps /apps/nwchem/data \
&& rm -rf $NWCHEM_TOP
