#
FROM ghcr.io/charliecpeterson/basebuild:ubuntu20.04-gcc10.3.0-oneapi2022.1.2 as build
ENV ARMCI_NETWORK=MPI-SPAWN 
ENV NWCHEM_TOP=/opt/nwchem-7.0.2-release 
ENV NWCHEM_TARGET=LINUX64 
ENV NWCHEM_MODULES="all" 
ENV BLASOPT=" -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core  -lpthread -lutil -lm -ldl" 
ENV LAPACK_LIB="-lmkl_intel_ilp64 -lmkl_sequential -lmkl_core  -lpthread -lutil -lm -ldl" 
ENV SCALAPACK_LIB=" -lmkl_scalapack_ilp64 -lmkl_blacs_intelmpi_ilp64 -lpthread -lutil -lm -ldl"  
ENV BLAS_SIZE=8 
ENV SCALAPACK_SIZE=8 
ENV USE_64TO32=y 
ENV USE_FPICF=y  
ENV USE_MPI=y 
ENV USE_MPIF=y 
ENV USE_MPIF4=y 
ENV FC=ifort 
ENV CC=icc 
ENV CXX=icpc
RUN apt update ; apt-get install -y --no-install-recommends  gcc-multilib  openssl libssl-dev ssh wget make git curl wget  \
  && cd /opt ;curl -SL   https://github.com/nwchemgit/nwchem/archive/refs/tags/v7.0.2-release.tar.gz  | tar xzf - \
  && cd $NWCHEM_TOP/src \
  &&  sed -i 's/nb=500/nb=1000/g' atomscf/cguess.fh \
  && make FC=ifort CC=icc CXX=icpc \
  && mkdir -pv /apps/nwchem/bin \
  && mkdir -pv /apps/nwchem/data \
  && cp $NWCHEM_TOP/bin/${NWCHEM_TARGET}/nwchem /apps/nwchem/bin \
  && cd /apps/nwchem/bin \
  && chmod 755 nwchem \
  && cd $NWCHEM_TOP/src/basis \
  && cp -r libraries /apps/nwchem/data \
  && cd $NWCHEM_TOP/src \
  && cp -r data /apps/nwchem/ \
  && cd $NWCHEM_TOP/src/nwpw \
  && cp -r libraryps /apps/nwchem/data \
  && rm -rf $NWCHEM_TOP  

FROM ghcr.io/charliecpeterson/baserun:ubuntu20.04-gcc10.3.0-oneapi2022.1.2
COPY --from=build /apps/ /apps/
ENV NWCHEM_DIR=/apps/nwchem
ENV PATH=${NWCHEM_DIR}/bin:$PATH
ENV NWCHEM_BASIS_LIBRARY=${NWCHEM_DIR}/data/libraries/
ENV NWCHEM_NWPW_LIBRARY=${NWCHEM_DIR}/data/libraryps/
ENV FFIELD=amber
ENV AMBER_1=${NWCHEM_DIR}/data/amber_s/
ENV AMBER_2=${NWCHEM_DIR}/data/amber_q/
ENV AMBER_3=${NWCHEM_DIR}/data/amber_x/
ENV AMBER_4=${NWCHEM_DIR}/data/amber_u/
ENV SPCE=${NWCHEM_DIR}/data/solvents/spce.rst
ENV CHARMM_S=${NWCHEM_DIR}/data/charmm_s/
ENV CHARMM_X=${NWCHEM_DIR}/data/charmm_x/

