#
FROM ghcr.io/charliecpeterson/base:build-ubuntu20.04-gcc8.5.0-oneapi2022.1.2 as build


RUN export bupLD=$LD_LIBRARY_PATH ; unset LD_LIBRARY_PATH ; apt-get update  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget curl make git  liblzma-dev  libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libbz2-dev \
    && export LD_LIBRARY_PATH=$bupLD \
    && cd /tmp ; curl -SL  curl -SL https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tgz | tar xzf - \
    && cd Python-2.7.16 ; ./configure --prefix=/apps/python \
    && make ; make install \
    && cd /tmp ; rm -r Python-2.7.16 



ENV PATH=/apps/python/bin:$PATH
ENV LD_LIBRARY_PATH=/apps/python/lib:$LD_LIBRARY_PATH

RUN cd /tmp ;curl -SL  https://zenodo.org/record/3572669/files/DIRAC-19.0-Source.tar.gz  | tar xzf - \
  && cd DIRAC-19.0-Source \
## Fix output for convert4qmc
  && sed -i 's/100  FORMAT(3X,I5,2X,A12,2X,4F14.10)/100  FORMAT(3X,I5,2X,A12,2X,4F20.10)/g' src/dirac/dirout.F \
  && export PATH=/apps/dirac/bin:/apps/python/bin:$PATH \ 
  && export LD_LIBRARY_PATH=/apps/python/lib:$LD_LIBRARY_PATH \
  && export MATH_ROOT=$MKLROOT \
  && ./setup --fc=mpif90 --cc=mpicc --cxx=mpicxx --mpi  --prefix=/apps/dirac \
  && cd build ; make ; make install

FROM ghcr.io/charliecpeterson/base:run-ubuntu20.04-gcc8.5.0-oneapi2022.1.2
COPY --from=build /apps/ /apps/
ENV PATH=/apps/dirac/bin:/apps/python/bin:$PATH
ENV LD_LIBRARY_PATH=/apps/python/lib:$LD_LIBRARY_PATH


