#
FROM ghcr.io/charliecpeterson/basebuild:ubuntu21.04-gcc10.3.0-oneapi2022.1.2 as build
ENV PATH=/apps/python/bin:$PATH
ENV LD_LIBRARY_PATH=/apps/python/lib:$LD_LIBRARY_PATH
RUN apt-get update  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    libffi-dev wget liblzma-dev  libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev \
    && cd /tmp ; wget https://www.python.org/ftp/python/3.9.10/Python-3.9.10.tgz \
    && tar -vxf Python-3.9.10.tgz ; rm Python-3.9.10.tgz  \
    && cd Python-3.9.10 ; ./configure --prefix=/apps/python \
    && make ; make install \
    && cd /tmp ; rm -r Python-3.9.10 \
    &&  pip3 install irpf90 \
    && pip3 install docopt \
    && ln -s /apps/python/bin/python3 /apps/python/bin/python

RUN apt update ; DEBIAN_FRONTEND=noninteractive  apt-get install -y --no-install-recommends  software-properties-common libzmq3-dev libncurses5-dev pkg-config libgmp3-dev m4 bubblewrap libcap-dev ninja-build make curl wget  \
  && add-apt-repository ppa:avsm/ppa \ 
  &&  apt update ; apt install  -y --no-install-recommends  opam \
  && opam init --disable-sandboxing
  && cd /tmp ;curl -SL  https://github.com/QuantumPackage/qp2/archive/refs/tags/2.1.2.tar.gz   | tar xzf - \
  && cd qp2-2.1.2 \
  && ./configure --install=irpf90 \
  && ./configure --install=zeromq \
  && ./configure --install=f77zmq \
  && ./configure --install=ocaml \
  && ./configure 

FROM ghcr.io/charliecpeterson/baserun:ubuntu21.04-gcc10.3.0-oneapi2022.1.2
COPY --from=build /apps/ /apps/
ENV PATH=/opt/nwchem/bin:$PATH

