# Base GCC/Oneapi building container image
# Rocky 9.0
# Charles Peterson <charliecpeterson@gmail.com>
# Created 7/2022

#Bulding Cmake
FROM rockylinux:9.0 as buildcmake
RUN yum -y update \
    && yum install -y  \
    ca-certificates curl  
RUN cd /opt  \
    && curl -LO https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2-linux-x86_64.sh \
    && mkdir -p /opt/cmake  \
    && /bin/bash cmake-3.20.2-linux-x86_64.sh --prefix=/opt/cmake --skip-license
RUN rm -rf /opt/cmake/include \
    && rm -rf /opt/cmake/lib/pkgconfig 
RUN rm -rf /opt/cmake/share/doc
RUN rm -rf /opt/cmake/share/man
RUN rm -rf /opt/cmake/man

FROM rockylinux:9.0

ENV gcc_VER=11.3.0

ENV oneapi_compiler_dpcpp_cpp_VER=2022.1.0
ENV oneapi_mkl_VER=2022.1.0

ENV oneapi_compiler_fortran_VER=2022.1.0
ENV oneapi_compiler_dpcpp_cpp_and_cpp_classic_VER=2022.1.0
ENV oneapi_mpi_VER=2021.6.0


COPY ./oneAPI.repo /etc/yum.repos.d/oneAPI.repo

RUN yum -y update  \
    && yum update -y \
    && yum install -y  \
    intel-oneapi-compiler-dpcpp-cpp-runtime-${oneapi_compiler_dpcpp_cpp_VER} \
    intel-oneapi-runtime-mkl-${oneapi_mkl_VER} \
    intel-oneapi-compiler-fortran-runtime-${oneapi_compiler_fortran_VER} \
    intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-runtime-${oneapi_compiler_dpcpp_cpp_and_cpp_classic_VER} \
    intel-oneapi-runtime-mpi-${oneapi_mpi_VER}


RUN yum -y update  \
    && yum install -y pkgconfig bzip2 gcc gcc-c++ make wget curl flex \
    && yum groupinstall -y "Development Tools" \
    && cd /tmp ; wget https://ftp.gnu.org/gnu/gcc/gcc-${gcc_VER}/gcc-${gcc_VER}.tar.gz \
    && tar -vxf gcc-${gcc_VER}.tar.gz ; rm gcc-${gcc_VER}.tar.gz \
    && cd gcc-${gcc_VER} ; ./contrib/download_prerequisites  \
    && mkdir build ; cd build \
    && ../configure --build=x86_64-linux-gnu --disable-multilib  --enable-languages=c,c++,fortran --prefix=/opt/gcc \
    && make -j "$(nproc)" && make install-strip \
    && cd /tmp ; rm -rf gcc-${gcc_VER} 

COPY --from=buildcmake /opt/cmake/ /opt/cmake/

ENV TBBROOT=/opt/intel/oneapi/tbb/2021.6.0/env/..
ENV ONEAPI_ROOT=/opt/intel/oneapi
ENV PKG_CONFIG_PATH=/opt/intel/oneapi/tbb/2021.6.0/env/../lib/pkgconfig:/opt/intel/oneapi/mpi/2021.6.0/lib/pkgconfig:/opt/intel/oneapi/compiler/2022.1.0/lib/pkgconfig
ENV I_MPI_ROOT=/opt/intel/oneapi/mpi/2021.6.0
ENV FI_PROVIDER_PATH=/opt/intel/oneapi/mpi/2021.6.0//libfabric/lib/prov:/usr/lib64/libfabric
ENV DIAGUTIL_PATH=/opt/intel/oneapi/compiler/2022.1.0/sys_check/sys_check.sh
ENV MANPATH=/opt/intel/oneapi/mpi/2021.6.0/man:/opt/intel/oneapi/compiler/2022.1.0/documentation/en/man/common::
ENV CMAKE_PREFIX_PATH=/opt/intel/oneapi/tbb/2021.6.0/env/..:/opt/intel/oneapi/compiler/2022.1.0/linux/IntelDPCPP
ENV CMPLR_ROOT=/opt/intel/oneapi/compiler/2022.1.0
ENV LIBRARY_PATH=/opt/intel/oneapi/tbb/2021.6.0/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.6.0//libfabric/lib:/opt/intel/oneapi/mpi/2021.6.0//lib/release:/opt/intel/oneapi/mpi/2021.6.0//lib:/opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/compiler/2022.1.0/linux/lib
ENV OCL_ICD_FILENAMES=/opt/intel/oneapi/compiler/2022.1.0/linux/lib/x64/libintelocl.so
ENV CLASSPATH=/opt/intel/oneapi/mpi/2021.6.0//lib/mpi.jar
ENV LD_LIBRARY_PATH=/opt/gcc/lib:/opt/gcc/lib64:/opt/intel/oneapi/tbb/2021.6.0/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.6.0//libfabric/lib:/opt/intel/oneapi/mpi/2021.6.0//lib/release:/opt/intel/oneapi/mpi/2021.6.0//lib:/opt/intel/oneapi/compiler/2022.1.0/linux/lib:/opt/intel/oneapi/compiler/2022.1.0/linux/lib/x64:/opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin
ENV NLSPATH=/opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/locale/%l_%t/%N
ENV PATH=/opt/gcc/bin:/opt/intel/oneapi/mpi/2021.6.0//libfabric/bin:/opt/intel/oneapi/mpi/2021.6.0//bin:/opt/intel/oneapi/compiler/2022.1.0/linux/bin/intel64:/opt/intel/oneapi/compiler/2022.1.0/linux/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV CPATH=/opt/intel/oneapi/tbb/2021.6.0/env/../include:/opt/intel/oneapi/mpi/2021.6.0//include

