#  
FROM ubuntu:23.04
ENV DEBIAN_FRONTEND=noninteractive
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
ENV PATH=/apps/python/bin:$PATH
ENV LD_LIBRARY_PATH=/apps/boost/lib:/apps/ga/lib:/apps/python/lib:$LD_LIBRARY_PATH
ENV BOOST_ROOT=/apps/boost

RUN DEBIAN_FRONTEND=noninteractive apt update ; apt-get install -y --no-install-recommends \ 
      make cmake ca-certificates wget curl liblzma-dev  libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev \
     gpg gcc gfortran \
     libhdf5-dev libgsl-dev git ssh curl  gcc-multilib

RUN apt-get update  \
    &&  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends binutils libc6-dev gpg-agent wget gnupg curl  ca-certificates  \
    && wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
    | gpg --dearmor |  tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" |  tee /etc/apt/sources.list.d/oneAPI.list 

RUN apt-get update  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       intel-basekit-2023.1.0  intel-hpckit-2023.1.0


RUN cd /tmp ; curl -SL  https://www.python.org/ftp/python/3.9.10/Python-3.9.10.tgz | tar xzf - \
    && cd Python-3.9.10 ; ./configure --prefix=/apps/python \ 
    && make ; make install \
    && cd /tmp ; rm -r Python-3.9.10 \
    && pip3 install pyparsing

RUN bash -c "source /opt/intel/oneapi/setvars.sh  \
  && cd /tmp ; curl -SL https://github.com/GlobalArrays/ga/releases/download/v5.8.1/ga-5.8.1.tar.gz | tar xzf - \
  &&  cd ga-5.8.1/ ; ./autogen.sh ; FC=ifort CC=icc CXX=icpc MPIF77=mpiifort MPICC=mpiicc MPICXX=mpiiicpc ./configure --enable-i8 --enable-shared --with-lapack=-mkl  --with-scalapack8 --with-blas8  --prefix=/apps/ga \
  && make ; make install \
  && cd /tmp ; rm -rf ga-5.8.1 "

RUN bash -c "source /opt/intel/oneapi/setvars.sh  \
  && cd /tmp ; curl -SL https://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.gz/download | tar xzf - \
  && cd boost_1_56_0 \
  && ./bootstrap.sh  --with-libraries=program_options,filesystem,system,serialization,thread --prefix=/apps/boost \
  && ./b2 install \
  && cd /tmp ; rm -rf boost_1_56_0"

RUN bash -c "source /opt/intel/oneapi/setvars.sh  \
  && cd /tmp ;curl -SL  https://gitlab.com/Molcas/OpenMolcas/-/archive/v23.06/OpenMolcas-v23.06.tar.gz  | tar xzf - \
  && cd OpenMolcas-v23.06/  \
  && mkdir -p build ; cd build \
#  && GAROOT=/apps/ga FC=mpiifort CC=mpiicc CXX=mpiicpc cmake -DGA=ON -DLINALG=MKL -DOPENMP=ON -DCMAKE_INSTALL_PREFIX=/apps/openmolcas -DDMRG=ON  -DNEVPT2=ON ../ \
  && GAROOT=/apps/ga FC=mpiifort CC=mpiicc CXX=mpiicpc cmake -DGA=ON -DLINALG=MKL -DOPENMP=ON -DCMAKE_INSTALL_PREFIX=/apps/openmolcas   ../ \
  && make ; make install  \
  && cd /tmp ; rm -rf OpenMolcas-v23.06"

#FROM ghcr.io/charliecpeterson/base:run-ubuntu20.04-gcc8.5.0-oneapi2022.1.2
#RUN bupLD=$LD_LIBRARY_PATH ; unset LD_LIBRARY_PATH ; apt-get update  \
#    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libgsl-dev libhdf5-dev \
#    && LD_LIBRARY_PATH=$bupLD \
#    && rm -rf /var/lib/apt/lists/* 
#COPY --from=build /apps/ /apps/
#ENV PATH=/apps/openmolcas/bin:/apps/openmolcas:$PATH
#ENV PATH=/apps/python/bin:$PATH
#ENV LD_LIBRARY_PATH=/apps/openmolcas/lib:/apps/boost/lib:/apps/ga/lib:/apps/python/lib:$LD_LIBRARY_PATH

