#
FROM ghcr.io/charliecpeterson/basebuild:ubuntu20.04-gcc8.5.0-oneapi2022.1.2 as build
ENV FC=ifort
ENV FC_FLAGS="-O3 -save -mkl=sequential"
ENV FC_MPILD="-mkl=sequential"
ENV FC_MPI=mpiifort
ENV OMPI_FC=ifort
ENV FC_LD="-mkl=sequential"
ENV CC=icc
ENV CXX=icpc
ENV GRASP="/apps/grasp"

RUN apt update ; apt-get install -y --no-install-recommends  gcc-multilib wget make git curl wget  \
  && mkdir -pv /apps ; cd /apps \
  && git clone https://github.com/compas/grasp \
  && cd grasp \
  && git checkout 966fd6d154bd421033cf2cf56eb203d521a79e2e \
  && ./configure.sh ; cd build \
  && make ; make install


FROM ghcr.io/charliecpeterson/baserun:ubuntu20.04-gcc8.5.0-oneapi2022.1.2
COPY --from=build /apps/grasp /apps/grasp
ENV GRASP="/apps/grasp"
ENV PATH=/apps/grasp/bin:$PATH
ENV LD_LIBRARY_PATH=/apps/grasp/lib:$LD_LIBRARY_PATH
