#  
FROM charliecpeterson/basebuild:ubuntu20.04-gcc8.5.0-oneapi2022.1.2 as build
ENV DEBIAN_FRONTEND=noninteractive
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
ENV LD_LIBRARY_PATH=/opt/boost/lib:$LD_LIBRARY_PATH
ENV BOOST_ROOT=/opt/boost

RUN apt-get update  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    libhd5f-dev

RUN cd /opt ; curl -SL https://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.gz/download | tar xzf - \
  && cd boost_1_56_0 \
  && ./bootstrap.sh --prefix=/opt/boost \
  && ./b2 install \
  && cd /opt ; rm -rf boost_1_56_0

RUN cd /opt ;curl -SL  https://github.com/QMCPACK/qmcpack/archive/refs/tags/v3.12.0.tar.gz  | tar xzf - \
  && cd v3.12.0/build \
  && cmake -DCMAKE_C_COMPILER=mpiicc -DCMAKE_CXX_COMPILER=mpiicpc -DCMAKE_INSTALL_PREFIX=/opt/qmcpack .. \
  && make ; make install  \
  && cd /opt ; rm -rf v3.12.0

FROM charliecpeterson/baserun:ubuntu20.04-gcc8.5.0-oneapi2022.1.2
RUN apt-get update  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libhd5f-dev \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /opt/ /opt/
ENV PATH=/opt/qmcpack/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/boost/lib:$LD_LIBRARY_PATH

