FROM ghcr.io/charliecpeterson/build:dev-rocky9.3-oneapi2024.1-cuda12.1
ENV PYTHON_VER=3.10.10
ENV TF_VERSION=2.16.1
ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64:$LD_LIBRARY_PATH
COPY scripts /scripts

ENV USE_ONEAPI=TRUE

RUN /scripts/install_python.sh

EXPOSE 8787

ENTRYPOINT ["/scripts/juypter-startup.sh"]
