# Charles Peterson <charliecpeterson@gmail.com>
# HybPiper container
# https://github.com/mossmatters/HybPiper
# Created 2/11/2022


FROM ubuntu:20.04


RUN apt-get update  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    time make wget pkg-config libgtk2.0-dev  build-essential  software-properties-common \
    git liblzma-dev libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

RUN wget https://www.python.org/ftp/python/3.9.10/Python-3.9.10.tgz \
    &&  tar -vxf Python-3.9.10.tgz ; rm Python-3.9.10.tgz  \
    && cd Python-3.9.10 ; ./configure \ 
    && make ; make install \
    && cd ../ ; rm -r Python-3.9.10

RUN pip3 install biopython
RUN wget http://ftp.ebi.ac.uk/pub/software/vertebrategenomics/exonerate/exonerate-2.2.0.tar.gz \
    && tar -vxf exonerate-2.2.0.tar.gz ; rm exonerate-2.2.0.tar.gz \
    && cd exonerate-2.2.0 ; ./configure \ 
    && make CFLAGS='-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include' CPPFLAGS='-I/usr/lib/x86_64-linux-gnu/glib-2.0/include' ; make install \
    && cd .. ; rm -rf exonerate-2.2.0 

RUN wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.12.0+-x64-linux.tar.gz \
    && mkdir -pv /opt/blast ; tar -vxf ncbi-blast-2.12.0+-x64-linux.tar.gz -C /opt/blast \
    && rm ncbi-blast-2.12.0+-x64-linux.tar.gz

ENV PATH=$PATH:/opt/blast/ncbi-blast-2.12.0+/bin

RUN wget https://cab.spbu.ru/files/release3.15.4/SPAdes-3.15.4-Linux.tar.gz \
    && mkdir -pv /opt/spades ; tar -vxf SPAdes-3.15.4-Linux.tar.gz -C /opt/spades \
    && rm SPAdes-3.15.4-Linux.tar.gz

ENV PATH=$PATH:/opt/spades/SPAdes-3.15.4-Linux/bin

RUN wget https://ftp.gnu.org/gnu/parallel/parallel-20220122.tar.bz2 \
    && tar -vxf parallel-20220122.tar.bz2 ; rm parallel-20220122.tar.bz2 \
    && cd parallel-20220122 ; ./configure \
    && make ; make install \ 
    && cd .. ; rm -rf parallel-20220122/ 

RUN wget https://github.com/lh3/bwa/releases/download/v0.7.17/bwa-0.7.17.tar.bz2 \
    && tar -vxf bwa-0.7.17.tar.bz2 ; rm bwa-0.7.17.tar.bz2 \
    && cd bwa-0.7.17/ ; make \
    && mkdir -pv /opt/bwa/bin ; cp bwa /opt/bwa/bin \
    && cd .. ; rm -rf bwa-0.7.17

ENV PATH=$PATH:/opt/bwa/bin

RUN wget https://github.com/samtools/samtools/releases/download/1.14/samtools-1.14.tar.bz2 \
    && tar -vxf samtools-1.14.tar.bz2 ; rm samtools-1.14.tar.bz2 \
    && cd samtools-1.14 ; ./configure ; make ; make install \
    && cd .. ; rm -rf samtools-1.14

RUN cd /opt ; git clone https://github.com/mossmatters/HybPiper \ 
    && cd HybPiper ; git checkout v1.3.1

ENV hybpiper=/opt/HybPiper
    

